version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    wrapcheck:
      ignore-sig-regexps:
        - \.New.*Error\(
        - \.Wrap.*Error\(
  exclusions:
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - path: (.+)_test.go
        linters:
          - dupl
          - err113
          - funlen
          - wsl

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(sensor-stream-server)

issues:
  max-issues-per-linter: 0 # Set to 0 to disable.
  max-same-issues: 0 # Set to 0 to disable.

run:
  timeout: 5m
