name: Build Node

on:
  pull_request:
    paths:
      - "node/**"
  push:
    branches: ["main"]
    paths:
      - "node/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create secrets.h from template
        run: cp node/main/secrets.template.h node/main/secrets.h

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32c6
          path: node/
